### PR TITLE
Add support for schedule overrides

### PR DESCRIPTION
**Pull request by scarytom**
Support the `POST schedules/:schedule_id/overrides` API call, as described here https://developer.pagerduty.com/documentation/rest/schedules/overrides/create

### CODE REVIEW

**Comment by scarytom** [comment]
Hopefully this is a pretty uncontroversial pull-request, as it just adds support for one more API call.  If you could take this and publish version 1.0.7 to rubygems, that will enable me to add features to the lita-pagerduty plugin.  Thanks.

**Comment by kryptek** [comment]
Jeez.. been so long since I look at all this code. Glad people still find it useful! The changes you're proposing /look/ safe. I'm okay merging this in. Unfortunately I never got around to finishing the rewrite with unit tests. It'd be nice if I could pick that up again..

**Comment by scarytom** [comment]
Yes, it is useful -- thanks for creating it.  Are you going to publish a new version of the gem?

**Comment by kryptek** [comment]
Updated gem to version 1.0.9. There was a previous commit I merged in where someone bumped from 1.0.6 to 1.0.8.. I never built the gem with those changes so I've went ahead and pushed the newer gem to RubyGems.

**Comment by kryptek** [comment]
@scarytom I'd love to.. the code is much cleaner in the state it's in and I implemented unit tests with VCR. Unfortunately with work at AWS being so busy, I ran out of development time with my free account on pagerduty. If I had open ended access to the API to continue development I wouldn't mind finishing it up

**Pull request merged**
